name: 🐞 Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to file a bug!"
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: e.g. 1.2.3
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Affected area
      description: Which part of the product is affected?
      options:
        - |-
          Frontend
          <!-- automation: area=frontend -->
        - |-
          Backend
          <!-- automation: area=backend -->
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I searched existing issues for duplicates
          required: true