on:
  push: {}
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        default: bar
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.foo == 'null' }}
    - run: echo ${{ inputs.foo == null }}
