on:
  push: {}
jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
    - run: env | sort
    - run: |
        cat > .github/workflows/foo.yml << EOF
        on:
          workflow_call: {}
        jobs:
          j:
            runs-on: ubuntu-latest
            steps:
            - run: |
                echo Hello world!
        EOF
  j2:
    needs: j1
    uses: ./.github/workflows/foo.yml
    
