on:
  push: {}
  workflow_dispatch:
    inputs:
      foo:
        description: ${{ 'foo' }}
        required: ${{ 'true' }}
        default: ${{ 'bar' }}

env:
  FOO: bar

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - run: 
