on:
  push: {}
jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
    - run: env | sort
    - run: |
        mkdir -p actions/foo
        cat > actions/foo/action.yml << EOF
        name: Foo
        runs:
          using: composite
          steps:
            - run: echo "Hello, world"
              shell: bash
        EOF
    - uses: ./actions/foo
    
