on:
  push: {}
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        required: true
        default: ${{ 'bar' }}
        type: ${{ 'string' }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - run: 
