on:
  push: {}
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        default: bar
        type: string

jobs:
  main:
    defaults:
      run:
        shell: ${{ inputs.foo || 'bash' }}
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello
