on:
  push: {}
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        default: bar
        type: string

env:
  FOO: ubuntu-latest

jobs:
  j:
    runs-on: ${{ env.FOO }}
    steps:
    - run: echo Hello
