on:
  push: {}
  workflow_dispatch:
    inputs:
      foo:
        description: foo
        default: bar
        type: string

defaults:
  run:
    shell: ${{ inputs.foo || 'bash' }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello
