on:
  - push
  - workflow_dispatch

env:
  FOO: bar

jobs:
  main:
    strategy:
      matrix:
        x: [a]
    runs-on: ubuntu-latest
    outputs:
      x: ${{ matrix.x }}
    steps:
      - run: echo ${{ env.FOO }}

  bla:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - run: echo ${{ needs.main.outputs.x }}
