on:
  workflow_dispatch: {}
  push: {}

jobs:
  prepare:
    outputs:
      runner: ${{ steps.foo.outputs.runner }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo runner=ubuntu-latest >> $GITHUB_OUTPUTS
        id: foo
        if: false
  maybe:
    needs: [prepare]
    runs-on: ${{ needs.prepare.outputs.runner }}
    if: ${{ needs.prepare.outputs.runner }}
    steps:
      - run: echo whoops
